sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker

before_install:
    - cd docker/dev
    - docker-compose up -d
    - cd ../..
    
#before_script: cd src

script: 
    - mvn clean install -P test-business,test-consumer
    - mvn cobertura:cobertura
    
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sbt coveralls
  
    
after_script:
    - cd docker/dev
    - docker-compose stop
    - docker-compose rm -v -f
    
notifications:
  email:
    recipients:
      - ceremej@gmail.com
    on_success: always 
    on_failure: always 
