language: java
services:
  - docker

before_install:
    - cd docker/dev
    - docker-compose up -d
    - cd ../..
    
before_script: cd src

script: 
    - mvn clean install -P test-business,test-consumer
    
after_script:
    - cd docker/dev
    - docker-compose stop
    - docker-compose rm -v -f
    
notifications:
  email:
    recipients:
      - ceremej@gmail.com
    on_success: always 
    on_failure: always 
