language: java
services:
  - docker

script: mvn clean test -P test-consumer,test-business

notifications:
  email:
    recipients:
      - ceremej@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
